- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/docker-setup.yml