- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/docker-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/latex-setup.yml
    - include_tasks: tasks/conda-setup.yml
    - include_tasks: tasks/aws-cli-setup.yml
    # - include_tasks: tasks/trivy-setup.yml
