- name: Install Docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
