- name: Add NodeSource repository
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_20.x
    dest: /tmp/nodesource_setup.sh
  tags:
    - install
    - node

- name: Run NodeSource setup script
  become: true
  ansible.builtin.command:
    cmd: bash /tmp/nodesource_setup.sh
  tags:
    - install
    - node

- name: Install Node.js
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
  tags:
    - install
    - node

- name: Npmjs prefix
  become: true
  ansible.builtin.command:
    cmd: mkdir -p ~/.local/.npm-global
  tags:
    - install
    - node

- name: Ensure npm is installed
  become: true
  ansible.builtin.command:
    cmd: npm --version
  register: npm_check
  ignore_errors: yes
  tags:
    - install
    - node

- name: Npmjs global settings
  become: true
  ansible.builtin.command:
    cmd: npm config set prefix '~/.local/.npm-global'
  when: npm_check.rc == 0
  tags:
    - install
    - node

- name: Add npmjs to PATH
  become: true
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "export PATH=~/.local/.npm-global/bin:$PATH"
    state: present
  tags:
    - install
    - node

- name: Install N
  become: true
  npm:
    name: n
    global: true
  register: install_n
  tags:
    - install
    - node

- name: Install correct version of Node
  become: true
  ansible.builtin.shell: ~/.local/bin/n 20
  when: install_n.changed
  tags:
    - install
    - node
